Реализована логика для работы с user'ами и item'ами согласно ТЗ 13 сп…
Eenot/java-shareit pull request #1
Opened 2024-03-23 15:05 UTC by Eenot

…ринта.

2024-03-23 18:58 UTC, Fleaman777 requested changes

2024-03-23 18:58 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return itemService.updateItem(itemDto, request.getIntHeader("X-Sharer-User-Id"));
X-Sharer-User-Id - можно вынести в константу

2024-03-23 18:58 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                    .filter(x -> x.getAvailable().equals(true))
можно попробовать сделать через метод референс Item::getAvailable

2024-03-23 18:58 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +        if (!user.getEmail().equals(users.get(user.getId()).getEmail())) {
много вложенных получений - ухудшают восприятие, лучше что-то вынести в отдельную локальную перменную,
и использовать эту переменную дальше

2024-03-23 18:58 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    }
Можно еще добавить проверку на существование пользователя с таким ID.

2024-03-23 18:58 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    private String email;
так же можно добавить @NotNull над email

2024-03-25 17:34 UTC, Eenot commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    }
В методе getItemsByUserId уже ведь есть проверка на существование пользователя. Нужна доп. проверка в контроллере?

2024-03-25 20:20 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    }
одной проверки будет достаточно, те сделал все правильно

2024-03-25 20:22 UTC, Fleaman777 requested changes
надо бы поправить гитхаб проверку, что бы она была зеленой

2024-03-27 11:08 UTC, Fleaman777 approved these changes

2024-04-03 18:03 UTC, merged